### ISSUE TITLE
The non-synonymous/synonymous rate ratio for test in datamonky represents the dn-ds of the entire gene ?

### ISSUE THREAD

**Issue by douluojiaofu** [veg/datamonkey-js#690] opened 2023-05-16 02:55 UTC
Dear doctor, Thank you for watching this question!

I'm using datamonky-slac to detect positive selection site,and I get a result.

I have seen in some articles that some researchers believe that the red content below is the dN-dS of the whole gene. I am not sure whether this index is the dN-dS of the whole gene??

I would really appreciate it if i could get your help!
![dbe481676c2d8710258acd5355ed852](https://github.com/veg/datamonkey-js/assets/105349016/80509c2e-f1ed-4968-9883-ef965be51b16)

**Comment by stevenweaver** [comment] 2023-06-22 19:24
Duplicate of veg/hyphy#1607

**Closed by stevenweaver** 2023-06-22 19:24 UTC
